Controllers/RookiesController.cs
using System.Runtime.Serialization.Json;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using C__ASP_.Net_Core_MVC_2.Models;
using System.Text.Json;

namespace C__ASP_.Net_Core_MVC_2.Controllers.Controllers
{
    public class RookiesController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public RookiesController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }
        static List<Person> members = new List<Person>
        {
            new Person{
                Id = 18,
                FirstName = "Long",
                LastName = "Bao",
                Gender = "Male",
                DateOfBirth = new DateTime(1994,1,16),
                PhoneNumber="",
                BirthPlace = "Bac Ninh",
                IsGraduated  = false,
                Age = 27
            },
            new Person{
                Id = 14,
                FirstName = "Dat",
                LastName = "Dam Tuan",
                Gender = "Male",
                DateOfBirth = new DateTime(1996,7,14),
                PhoneNumber="",
                BirthPlace = "Ha noi",
                IsGraduated  = true,
                Age = 25
            },
            new Person{
                Id = 11,
                FirstName = "Hung",
                LastName = "Ngo Quoc",
                Gender = "Male",
                DateOfBirth = new DateTime(1991,3,7),
                PhoneNumber="",
                BirthPlace = "Hai Phong",
                IsGraduated  = false,
                Age = 30
            },
            new Person{
                Id = 19,
                FirstName = "Van",
                LastName = "Nguyen Cong",
                Gender = "Male",
                DateOfBirth = new DateTime(1998,4,5),
                PhoneNumber="",
                BirthPlace = "Ha Noi",
                IsGraduated  = true,
                Age = 23
            },
            new Person{
                Id = 3,
                FirstName = "Trang",
                LastName = "Nguyen Huyen",
                Gender = "Female",
                DateOfBirth = new DateTime(2002,7,14),
                PhoneNumber="",
                BirthPlace = "Hai Duong",
                IsGraduated  = false,
                Age = 19
            },
            new Person{
                Id = 6,
                FirstName = "Ky",
                LastName = "Nguyen Khac",
                Gender = "Male",
                DateOfBirth = new DateTime(1999,11,12),
                PhoneNumber="",
                BirthPlace = "Ha Noi",
                IsGraduated  = false,
                Age = 22
            },
            new Person{
                Id = 8,
                FirstName = "Phuoc",
                LastName = "Hoang",
                Gender = "Male",
                DateOfBirth = new DateTime(2000,11,25),
                PhoneNumber="",
                BirthPlace = "Hai Phong",
                IsGraduated  = false,
                Age = 21
            },
            new Person{
                Id = 9,
                FirstName = "Hung",
                LastName = "Bui",
                Gender = "Male",
                DateOfBirth = new DateTime(1983,11,13),
                PhoneNumber="",
                BirthPlace = "Ha Noi",
                IsGraduated  = true,
                Age = 38
            }
        };
        public IActionResult Index()
        {
            return View(members);
        }
        public IActionResult Create()
        {

            return View();
        }

        [HttpPost]
        public IActionResult Create(Person model)
        {
            //Kiem tra 2 lop, tang tinh an toan, bao mat
            if (!ModelState.IsValid)
            {
                ViewBag.Error = "Invalid Model!";
                return View();
            }
            members.Add(model);
            return RedirectToAction("Index", members);
        }

        public IActionResult Edit(int id)
        {
            var model = members.FirstOrDefault(i => i.Id == id);
            return View(model);
        }

        [HttpPost]
        public IActionResult Edit(Person model)
        {
            //Kiem tra 2 lop, tang tinh an toan, bao mat
            if (!ModelState.IsValid)
            {
                ViewBag.Error = JsonSerializer.Serialize(model);
                return View();
            }
            var list = members.Where(p => p.Id != model.Id).ToList();
            list.Insert(0, model);
            members = list;
            return RedirectToAction("Index");
        }

        // public IActionResult Delete(int id)
        // {
        //     var model = members.FirstOrDefault(i => i.Id == id);
        //     return View(model);
        // }

        public IActionResult Delete(Person model)
        {
            var list = members.Where(p => p.Id != model.Id).ToList();
            members = list;
            return RedirectToAction("Index");
        }

        public IActionResult Privacy()
        {
            return View();
        }
        public IActionResult GetFullNames()
        {
            var names = members.Select(mb => $"{mb.LastName} {mb.FirstName}").ToList();
            return View("ViewGetFullNamePerson", names);
            // return Json(names);
        }
        public IActionResult GetPersonByGender()
        {
            var student = members.Where(s => s.Gender == "Male").ToList();
            return View("ViewGetPersonByGender", student);
            // var json = JsonSerializer.Serialize(names);
            // return Content(json);
        }
        public IActionResult GetOldestPerson()
        {
            var biggest = members.Max(st => st.Age);
            System.Console.WriteLine(biggest);
            var oldest = members.Where(st => st.Age == biggest).ToList();
            var oldestTemp = oldest.FirstOrDefault();
            return View("ViewGetOldestPerson", oldestTemp);
        }
        public IActionResult GetPersonEqualsYear(int year)
        {
            var equal = members.Where(s => s.DateOfBirth.Year == year).ToList();
            return View("ViewGetPersonEqualsYear", equal);
        }
        public IActionResult GetPersonGreaterThanYear(int year)
        {
            var greater = members.Where(s => s.DateOfBirth.Year > year).ToList();
            return View("ViewGetPersonGreaterThanYear", greater);
        }
        public IActionResult GetPersonLessThanYear(int year)
        {
            var less = members.Where(s => s.DateOfBirth.Year < year).ToList();
            return View("ViewGetPersonLessThanYear", less);
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Rookies/Create.cshtml
@model Person
@{
    ViewData["Title"] = "Create New Person";
}
<div>
<a href="@Url.ActionLink("Index", "Rookies")" class="btn btn-info mr-5"><i class="fa fa-arrow-left mr-2" aria-hidden="true"></i>Back</a>
<h3 class="d-inline-block mb-0">@ViewData["Title"]</h3>
</div>
    <hr />
        <div>@ViewBag.Data</div>
<div class="row">
    <div class="col-6 offset-3">
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName)
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName)
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender)
                @Html.EditorFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateOfBirth)
                @Html.EditorFor(model => model.DateOfBirth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber)
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email)
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BirthPlace)
                @Html.EditorFor(model => model.BirthPlace, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BirthPlace, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </div>

    </div>
}
</div>
</div>

Views/Rookies/Edit.cshtml
@model Person
@{
    ViewData["Title"] = "Edit Person";
}
<div>
<a href="@Url.ActionLink("Index", "Rookies")" class="btn btn-info mr-5"><i class="fa fa-arrow-left mr-2" aria-hidden="true"></i>Back</a>
<h3 class="d-inline-block mb-0">@ViewData["Title"]</h3>
</div>
    <hr />
        <div>@ViewBag.Data</div>
<div class="row">
    <div class="col-6 offset-3">
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName)
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName)
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender)
                @Html.EditorFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateOfBirth)
                @Html.EditorFor(model => model.DateOfBirth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateOfBirth, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber)
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email)
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BirthPlace)
                @Html.EditorFor(model => model.BirthPlace, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BirthPlace, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-6">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </div>

    </div>
}
</div>
</div>

Views/Rookies/Index.cshtml
@model List<Person>

@{
  ViewData["Title"] = "Rookies";
}

<div class="text-left">
  <h3 class="d-inline-block">Rookies</h3>
  <a href="@Url.ActionLink("Create", "Rookies")" class="btn btn-primary float-right"><i class="fa fa-plus-square-o mr-2"
      aria-hidden="true"></i>Creat New Person</a>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Id</th>
        <th scope="col">FullName</th>
        <th scope="col">Gender</th>
        <th scope="col">BirthDay</th>
        <th scope="col">Age</th>
        <th class="text-center">Actions</th>
      </tr>
    </thead>
    <tbody>
      @{
        int @index = 1;
        foreach (var item in Model)
        {
          <tr>
            <th scope="row">@(index++)</th>
            <td>@item.Id</td>
            <td>@item.FullNames</td>
            <td>@item.Gender</td>
            <td>@item.DateOfBirth.ToString("dd/MM/yyyy")</td>
            <td>@item.Age</td>
            <td class="text-center" width=200px>
              <a href="@Url.ActionLink("Edit", "Rookies", new {id = item.Id})" class="btn btn-secondary btn-sm"
              role="button"><i class="fa fa-pencil mr-2" aria-hidden="true"></i>Edit</a>
              <a onclick="Delete(@item.Id)" href="#" class="btn btn-danger btn-sm" role="button"><i
                class="fa fa-trash-o mr-2" aria-hidden="true"></i>Delete</a>
            </td>
          </tr>
        }
      }
    </tbody>
  </table>
  <nav aria-label="Page navigation example">
    <ul class="pagination">
      <li class="page-item">
        <a class="page-link" href="#" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
      <li class="page-item"><a class="page-link" href="#">1</a></li>
      <li class="page-item"><a class="page-link" href="#">2</a></li>
      <li class="page-item"><a class="page-link" href="#">3</a></li>
      <li class="page-item">
        <a class="page-link" href="#" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
    </ul>
  </nav>
</div>
<script>
  function Delete(Id) 
  {
    if (confirm("Are you sure you want to delete?"))
      location.href = `/Rookies/Delete?Id= + ${Id}`;
  }
</script>